Ada-Developers-Academy/core-unit-3

- config.yaml
- custom-snippets/reservation/.dockerignore
- custom-snippets/reservation/.gitignore
- custom-snippets/reservation/Dockerfile
- custom-snippets/reservation/package-lock.json
- custom-snippets/reservation/package.json
- custom-snippets/reservation/submission.test.js
- custom-snippets/reservation/test.sh
- custom-snippets/summarizeLibrary/.dockerignore
- custom-snippets/summarizeLibrary/.gitignore
- custom-snippets/summarizeLibrary/Dockerfile
- custom-snippets/summarizeLibrary/package-lock.json
- custom-snippets/summarizeLibrary/package.json
- custom-snippets/summarizeLibrary/submission.test.js
- custom-snippets/summarizeLibrary/test.sh
- custom-snippets/tool/.dockerignore
- custom-snippets/tool/.gitignore
- custom-snippets/tool/Dockerfile
- custom-snippets/tool/package-lock.json
- custom-snippets/tool/package.json
- custom-snippets/tool/submission.test.js
- custom-snippets/tool/test.sh
- custom-snippets/toolLibrary/.dockerignore
- custom-snippets/toolLibrary/.gitignore
- custom-snippets/toolLibrary/Dockerfile
- custom-snippets/toolLibrary/package-lock.json
- custom-snippets/toolLibrary/package.json
- custom-snippets/toolLibrary/submission.test.js
- custom-snippets/toolLibrary/test.sh
- problem-set-tool-library/problem-set-tool-library-wave-2.md
I have NOT tested the tests on a sandbox environment yet.
> Wave 2 of Tool Library

- adding-behavior/problem-set-adding-behavior.md
- config.yaml
Notifying @CheezItMan , because you so kindly offered to write a problem set for this topic.
This Problem Set is deleted because this is presented on the same day that "Event Handling" is, and Event Handling has a huge problem set attached to it ;) Students can focus on that one instead.
> deletes problem-set-adding-behavior

- learning-another-language/variables.md
Added a bit to the lesson on the scope of let-var and const.
> add scoping example for let-const-var

- structuring-content/problem-set-structuring-content.md
Optional change, definitely feel free to reject this change if you disagree!
I figured since this activity asks students to write HTML, it's reasonable to suggest how to do that in VS Code and how to view their rendered file.
However, I could buy the argument that this activity is meant to get the students to focus on the structure of the HTML and not how it's presented, so it would be distracting to have them look at the rendered file.
Up to you to decide!
> Add instructions on editing and viewing HTML

- adding-behavior/connecting-html-css-and-js.md
Just a minor change switching the "scripts" folder to "src" to match what students will see in CRA.
> Minor Change Adding Behavior scripts --> src to conform to CRA

- config.yaml
- learning-another-language/destructuring.md
- learning-another-language/objects.md
Added a destructuring lesson (need to think about lighting talks here).  Also fixed a typo.
I kept it basic, but could add more.
> Cm/learning another language - Destructuring Lesson

- calling-apis/problem-set-requests-with-js.md
This change does the same adjustments that were applied to unit 2 to try to avoid the drift issues in the unit 3 version as well.
> Apply unit 2 seven wonders updates to unit 3

- config.yaml
- Remove personal portfolio site activity from config
- Layout suggestions moved to personal portfolio site readme: https://github.com/AdaGold/personal-portfolio-site/pull/24
> 3) move layout suggestions to personal portfolio readme

- learning-another-language/classes.md
confirmed these solutions are bug free with replit.
> fix a few bugs in JS examples

- learning-another-language/vscode-and-style.md
Ticket: https://app.asana.com/0/1201700438643002/1203453152075977/f
- Fixed main typo reported in ticket
- Fixed several other misspellings in same file
- Added clarifying text for where the JSON snippet should be inserted
- Added json formatting hint
- Added line break in callout between paragraphs
> Bug Bash: Writing JavaScript Locally

- learning-another-language/objects.md
[asana ticket](https://app.asana.com/0/1201700438643002/1202373192958603/f)
> Fix wrong output in Learning a New Language: Objects lesson 

- react-components/jsx.md
Change for: https://app.asana.com/0/1205655776549324/1205889174265638/f
> Update JSX lesson to use Vite

- react-components/problem-set-recreating-components.md
Asana: https://app.asana.com/0/1205655776549324/1205889174265634/f
Minimal changes. Mostly just the setup command and some clarification around whether to use the landing page as shown.
> Port "React Components/Problem Set: Recreating Components" to use npm/vite

- state-and-event-handling/problem-set-recreate-weather-report.md
Asana ticket: https://app.asana.com/0/1205655776549324/1205962499927033/f
This updates the new project command and includes a link to a sample solution.
Solution PR: https://github.com/AdaAnswers/react-weather-report/pull/1
> Port "State and Event Handling/Problem Set: React Weather Report" to use npm/vite

- lifting-state-up/single-source-of-truth.md
Asana: https://app.asana.com/0/1205655776549324/1206266576107841/f
8cdc66c Add note about the change in name from isPresent to isPresentData
6616f8f Apply suggestions from code review
3158742 include trailing comma in studentData
2c3d600 update challenges to use aliased option style
648eafd revise final paragraph to provide more of a roadmap about where the refactor is going
84ab5ef provide key best practice details
8f3dd13 Use will rather than could to emphasize the importance of this change
7637d4e mark the presence props required
cd5729b move isPresent naming note to callout with expanded justification and best practice description
15ce420 expand reasoning for adding an id to the student data
> Port "Lifting State Up/Single Source of Truth" to use npm/vite

- lifting-state-up/passing-down-event-handlers.md
Asana ticket: https://app.asana.com/0/1205655776549324/1206266576107842/f
f39145c update challenge prompt to toggle code, and uses labeled multiple choice options
6688bf8 Updates multiple choice to labeled style
bbb2b6e updates the wrap-up paragraph with respect to toggling and what's coming up
b4e83e2 adjust props naming and explanations for toggling the presence of a student
40fe8e8 Prefer typically vocabulary "pass" for a value over "send"
ddfa179 adds callout for function-passing style when updating array piece of state
9c29d82 Update callout about array pieces of state to be a bit more interactive with a prompt and collapsed answer.
8c6cd51 Add callout to discuss the object spread with shorthand notation when updating a student
e7e7cbd rework section to be about toggling student …
> Port "Lifting State Up/Passing Down Event Handlers" to use npm/vite

- handling-forms/controlled-forms.md
- handling-forms/submitting-forms.md
- javascript-cont/vscode-and-style.md
- lifting-state-up/inspecting-react-state.md
- lifting-state-up/passing-down-event-handlers.md
- lifting-state-up/single-source-of-truth.md
- props/nested-components.md
- props/props.md
- props/proptypes.md
- react-components/components.md
- react-components/hello-world.md
- react-components/jsx.md
- react-components/styling-components.md
- state-and-event-handling/event-handling.md
- state-and-event-handling/updating-state.md
- state-and-event-handling/using-state.md
- tests/testing-in-node.md
- useeffect-and-calling-apis/calling-apis-from-components.md
- useeffect-and-calling-apis/useeffect-after-render.md
https://app.asana.com/0/1205655776549324/1206386553945409/f
Commenting out videos that are out of date after we switched to npm and Vite for Unit 3.
> Comment out videos that reference yarn and create-react-app

- react-components/problem-set-recreating-components.md
Asana: https://app.asana.com/0/1205655776549324/1206446393027089/f
Base solution PR:https://github.com/AdaAnswers/problem-set-recreating-components/pull/1
Styled solution PR: https://github.com/AdaAnswers/problem-set-recreating-components/pull/2
This adds a collapsilble region and links to the solution to the Learn Problem Set under React Components > Problem Set: Recreating Components.
> Create Solution for Recreating Components Problem Set (Learn)

- calling-apis/post-requests-with-axios.md
[Asana task](https://app.asana.com/0/1205655776549324/1204606344384814/f)
This PR covers updating the links in the "Calling APIs" > "POST requests with Axios" Learn lesson to point to the new Render deployment.`trip-api` has been ported to python and [deployed to Render ](https://trektravel.onrender.com)
I used the existing `trip-api` repo to hold the new Flask version:
- There is a deprecated branch with [the old Ruby code](https://github.com/AdaGold/trip-api/tree/ruby-version-deprecated)
- [the Flask version is now on `main`](https://github.com/AdaGold/trip-api)
> Update TrekTravel App deployment links

- learning-another-language/fizzbuzz.md
[Asana Ticket](https://app.asana.com/1/181459410160484/project/1205655776549324/task/1209559273043258?focus=true)
Changes
- Add note about video using online repl instead of running code locally
- Remove replit link
- Add instructions for creating a FizzBuzz project locally
> Remove Replit from "Learning Another Language" > "FizzBuzz"

- learning-another-language/summary-resources-and-next-steps.md
[Asana Task ](https://app.asana.com/1/181459410160484/project/1205655776549324/task/1209674040720691?focus=true)
Changes
- Update intro paragraph to reflect that folks are running code locally rather than using REPLs. 
- Change line at the end to better reflect that these topics are upcoming lessons.
> Update "Learning a new Language" > "Summary, Resources, and next steps" lesson to reflect new lesson order

- javascript-cont/semicolons.md
[Asana Task](https://app.asana.com/0/1205655776549324/1209559273043261/f)
[ASI-bug-example repo](https://github.com/AdaGold/ASI-bug-example) created for the lesson
Changes
- Add note that video is using an online JavaScript REPL
- Update links to point to repo
- Include explicit note about cloning the repo if folks want to follow along locally
> Remove Replit & update content for new flow: "JavaScript, Cont." > "Semicolons

- javascript-cont/objects.md
[Asana Task](https://app.asana.com/0/1205655776549324/1209559273043263/f)
[objects-demo-js repo](https://github.com/AdaGold/objects-demo-js) created for the lesson
Changes
- Adds note about video using an online REPL, 
- Replaces Replit with a repo
- Adds context about object literals needing to be part of an expression
- Adds missing semicolons to some of the code examples (added in the `objects-demo-js` repo as well)
> Remove Replit & update content for new flow: "JavaScript, Cont." > "Objects" 

- javascript-cont/semicolons.md
- javascript-cont/variables.md
[Asana task](https://app.asana.com/0/1205655776549324/1209559273043262/f)
[variable-demo-js](https://github.com/AdaGold/variable-demo-js) repo created for the lesson
Changes
- Remove Replit and link to repo in Variables lesson
- Add note about video using online REPL in Variables lesson
- Fix copy/paste error in Semicolons lesson
> Remove Replit & update content for new flow: "JavaScript, Cont." > "Variables" 

- javascript-cont/destructuring.md
[Asana Task](https://app.asana.com/0/1205655776549324/1209674040720692/f)
[destructuring-objects-js repo](https://github.com/AdaGold/destructuring-objects-js) created for the lesson
Outstanding Questions/Discussion
- I could use another opinion on if we want to keep the video with the note that I added, or if it would be better to comment out this video due to drift. I think it could still be useful, but the code examples are not exactly in the same order and have some minor value & spacing differences.
Changes
- Add note around video examples and IDE differences. 
- Change variable `name` in examples to `userName` to avoid DOM related namespace conflict VSCode brought up. 
- Add link to repo version of code examples for students to run. 
- Add value swap example shown in video to the …
> Review Destructuring Objects in JS lesson for new flow & add code example repo for student practice

- tests/reading-tests.md
[Asana Task](https://app.asana.com/0/1205655776549324/1209584030049895/f)
Changes
- Remove references to Replit. 
- Update last question to ordering a FizzBuzz test
> Remove Replit & update CFU Question in "Tests" > "Reading Tests"

- tests/test-syntax-detail.md
[Asana Task](https://app.asana.com/0/1205655776549324/1209559273043269/f)
Changes
- Change Replit reference to CodeSandbox as the tool students will have used in this lesson set
- Replaces last CFU question "What was your biggest takeaway..." with a multiple choice problem
> Remove Replit & update CFU Question in "Tests" > "Test Syntax Detail"

- adding-behavior/connecting-html-css-and-js.md
[Asana Task](https://app.asana.com/0/1205655776549324/1209559273043272/f)
[Repo created for this lesson](https://github.com/AdaGold/connecting-html-css-js-demo)
Changes
- Swap Replit link for repo. 
- Add note about video using online IDE. 
- Add missing semicolons in code examples.
> Remove Replit in "Adding Behavior" > "Connecting HTML, CSS, and JavaScript"

- adding-behavior/changing-the-dom.md
[Asana Task](https://app.asana.com/0/1205655776549324/1209559273043273/f)
[Repo created for this lesson](https://github.com/AdaGold/changing-the-dom-demo)
Changes
- Add note about online REPL to video. 
- Replace replit links with link to GitHub repo. 
- Update code examples to prefer single quotes.
> Remove Replit in "Adding Behavior" > "Changing the DOM"

- event-handling/foreshadowing-state.md
[Asana Task](https://app.asana.com/0/1205655776549324/1209559273291355/f)
[Repo created for this lesson](https://github.com/AdaGold/foreshadowing-state-demo)
Changes
- Add note about style differences & online REPL to video. 
- Replace replit links with link to GitHub repo. 
- Update code examples to prefer single quotes.
- Add missing semicolon in code example.
> Remove Replit in "Event Handling" > "Foreshadowing State"

- calling-apis/get-requests-with-axios.md
[Asana Task](https://app.asana.com/0/1205655776549324/1209559273291356/f)
[Repo created for this lesson](https://github.com/AdaGold/get-requests-with-axios-demo)
Changes
- Add note about online REPL to video. 
- Replace Replit links with GitHub repo.
- Replace content on adding a secret to Replit with setting up a local .env and using `dotenv` 
- Update Query Params code example to match repo.
- Update broken LocationIQ links.
> Remove Replit in "Calling APIs" > "GET Requests With axios"
